### ISSUE TITLE
convert hijri to gregorian date

### ISSUE THREAD

**Issue by jebraili** [mohamedsabil83/laravel-hijri#1]
thanks for this.
this code just convert gregorian to hijri, can you update this for convert hijri to gregorian date?

**Comment by mohamedsabil83** [comment]
Glad it helps you. You can do it like this:
```php
$hijri = '1440-09-29';
$timestamp = Hijri::hTime($hijri);
$greg = date('Y-m-d', $timestamp);
```
Don't forget to import `Hijri`. Also, I plan to update and enhance this package soon to be more clear and efficient.
